//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCruiser.Model.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCruiser.Model.Entities.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string AddressCity {
            get {
                return ResourceManager.GetString("AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is required..
        /// </summary>
        public static string AddressCityRequired {
            get {
                return ResourceManager.GetString("AddressCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AddressCountry {
            get {
                return ResourceManager.GetString("AddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country is required..
        /// </summary>
        public static string AddressCountryRequired {
            get {
                return ResourceManager.GetString("AddressCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number.
        /// </summary>
        public static string AddressHouseNumber {
            get {
                return ResourceManager.GetString("AddressHouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The house number is required..
        /// </summary>
        public static string AddressHouseNumberRequired {
            get {
                return ResourceManager.GetString("AddressHouseNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string AddressPostalCode {
            get {
                return ResourceManager.GetString("AddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The postal code is required..
        /// </summary>
        public static string AddressPostalCodeRequired {
            get {
                return ResourceManager.GetString("AddressPostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post box.
        /// </summary>
        public static string AddressPostBox {
            get {
                return ResourceManager.GetString("AddressPostBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string AddressStreet {
            get {
                return ResourceManager.GetString("AddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street is required..
        /// </summary>
        public static string AddressStreetRequired {
            get {
                return ResourceManager.GetString("AddressStreetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time shift.
        /// </summary>
        public static string AssignmentFrom {
            get {
                return ResourceManager.GetString("AssignmentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment From After To.
        /// </summary>
        public static string AssignmentFromAfterTo {
            get {
                return ResourceManager.GetString("AssignmentFromAfterTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment From Required.
        /// </summary>
        public static string AssignmentFromRequired {
            get {
                return ResourceManager.GetString("AssignmentFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time shift.
        /// </summary>
        public static string AssignmentUntil {
            get {
                return ResourceManager.GetString("AssignmentUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment Until Required.
        /// </summary>
        public static string AssignmentUntilRequired {
            get {
                return ResourceManager.GetString("AssignmentUntilRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment name.
        /// </summary>
        public static string AttachmentName {
            get {
                return ResourceManager.GetString("AttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment name is required..
        /// </summary>
        public static string AttachmentNameRequired {
            get {
                return ResourceManager.GetString("AttachmentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached by {0}  {1} on {2}..
        /// </summary>
        public static string AttachmentTitleExecutor {
            get {
                return ResourceManager.GetString("AttachmentTitleExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment type.
        /// </summary>
        public static string AttachmentType {
            get {
                return ResourceManager.GetString("AttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment type is required..
        /// </summary>
        public static string AttachmentTypeRequired {
            get {
                return ResourceManager.GetString("AttachmentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AttributeGroupName {
            get {
                return ResourceManager.GetString("AttributeGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string AuthenticatedUserLogin {
            get {
                return ResourceManager.GetString("AuthenticatedUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Code.
        /// </summary>
        public static string BookingRemarkResultCodeId {
            get {
                return ResourceManager.GetString("BookingRemarkResultCodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {0} on {1}.
        /// </summary>
        public static string CallAgentRemarkDisplayAudit1 {
            get {
                return ResourceManager.GetString("CallAgentRemarkDisplayAudit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by {0} {1}.
        /// </summary>
        public static string CallAgentRemarkDisplayAudit2 {
            get {
                return ResourceManager.GetString("CallAgentRemarkDisplayAudit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The outcome of the customer call is required..
        /// </summary>
        public static string CallAgentRemarkResultCodeRequired {
            get {
                return ResourceManager.GetString("CallAgentRemarkResultCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appointment booking period exceeds the provisioning period..
        /// </summary>
        public static string CapacityCycleConfigurationAppointmentBookingPeriodInvalid {
            get {
                return ResourceManager.GetString("CapacityCycleConfigurationAppointmentBookingPeriodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution period exceeds the validity period of this configuration..
        /// </summary>
        public static string CapacityCycleConfigurationExecutionPeriodInvalid {
            get {
                return ResourceManager.GetString("CapacityCycleConfigurationExecutionPeriodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution period .
        /// </summary>
        public static string CapacityCycleConfigurationExecutionPeriodLength {
            get {
                return ResourceManager.GetString("CapacityCycleConfigurationExecutionPeriodLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remark is required..
        /// </summary>
        public static string CapacityCycleConfigurationRemarkRequired {
            get {
                return ResourceManager.GetString("CapacityCycleConfigurationRemarkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string CapacityCycleConfigurationValidFrom {
            get {
                return ResourceManager.GetString("CapacityCycleConfigurationValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date should be set after the start date..
        /// </summary>
        public static string CapacityCycleConfigurationValidFromAfterTo {
            get {
                return ResourceManager.GetString("CapacityCycleConfigurationValidFromAfterTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date is required..
        /// </summary>
        public static string CapacityCycleConfigurationValidFromRequired {
            get {
                return ResourceManager.GetString("CapacityCycleConfigurationValidFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string CapacityCycleConfigurationValidTo {
            get {
                return ResourceManager.GetString("CapacityCycleConfigurationValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date is required..
        /// </summary>
        public static string CapacityCycleConfigurationValidToRequired {
            get {
                return ResourceManager.GetString("CapacityCycleConfigurationValidToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution start date {0} is invalid because it will cause overlapping execution periods..
        /// </summary>
        public static string CapacityCycleExecutionOverlap {
            get {
                return ResourceManager.GetString("CapacityCycleExecutionOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutionStart.
        /// </summary>
        public static string CapacityCycleExecutionStart {
            get {
                return ResourceManager.GetString("CapacityCycleExecutionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no capacity configuration active on {0}..
        /// </summary>
        public static string CapacityCycleNoActiveConfiguration {
            get {
                return ResourceManager.GetString("CapacityCycleNoActiveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreed.
        /// </summary>
        public static string CapacityCycleStatusAgreed {
            get {
                return ResourceManager.GetString("CapacityCycleStatusAgreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string CapacityCycleStatusFinal {
            get {
                return ResourceManager.GetString("CapacityCycleStatusFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string CapacityCycleStatusNew {
            get {
                return ResourceManager.GetString("CapacityCycleStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting on agreement.
        /// </summary>
        public static string CapacityCycleStatusWaiting {
            get {
                return ResourceManager.GetString("CapacityCycleStatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string CapacityRequestDisplayHoursRequested {
            get {
                return ResourceManager.GetString("CapacityRequestDisplayHoursRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} technicians.
        /// </summary>
        public static string CapacityRequestDisplayTechniciansRequested {
            get {
                return ResourceManager.GetString("CapacityRequestDisplayTechniciansRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours requested.
        /// </summary>
        public static string CapacityRequestHoursRequested {
            get {
                return ResourceManager.GetString("CapacityRequestHoursRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hours requested are required..
        /// </summary>
        public static string CapacityRequestHoursRequestedRequired {
            get {
                return ResourceManager.GetString("CapacityRequestHoursRequestedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The region is required..
        /// </summary>
        public static string CapacityRequestRegionId {
            get {
                return ResourceManager.GetString("CapacityRequestRegionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The region is required..
        /// </summary>
        public static string CapacityRequestRegionRequired {
            get {
                return ResourceManager.GetString("CapacityRequestRegionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreed.
        /// </summary>
        public static string CapacityRequestStatusAgreed {
            get {
                return ResourceManager.GetString("CapacityRequestStatusAgreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string CapacityRequestStatusFinal {
            get {
                return ResourceManager.GetString("CapacityRequestStatusFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string CapacityRequestStatusNew {
            get {
                return ResourceManager.GetString("CapacityRequestStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting on agreement.
        /// </summary>
        public static string CapacityRequestStatusWaiting {
            get {
                return ResourceManager.GetString("CapacityRequestStatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technicians requested.
        /// </summary>
        public static string CapacityRequestTechniciansRequested {
            get {
                return ResourceManager.GetString("CapacityRequestTechniciansRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The technician requested are required..
        /// </summary>
        public static string CapacityRequestTechniciansRequestedRequired {
            get {
                return ResourceManager.GetString("CapacityRequestTechniciansRequestedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plan start is required when visit is committed..
        /// </summary>
        public static string CheckPlannedStartOnCommit {
            get {
                return ResourceManager.GetString("CheckPlannedStartOnCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Name.
        /// </summary>
        public static string CommercialName {
            get {
                return ResourceManager.GetString("CommercialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CompanyRoleName {
            get {
                return ResourceManager.GetString("CompanyRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidFrom.
        /// </summary>
        public static string CompanyRoleValidFrom {
            get {
                return ResourceManager.GetString("CompanyRoleValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidUntil.
        /// </summary>
        public static string CompanyRoleValidUntil {
            get {
                return ResourceManager.GetString("CompanyRoleValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string CompanyVAT {
            get {
                return ResourceManager.GetString("CompanyVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Comment.
        /// </summary>
        public static string ContactComment {
            get {
                return ResourceManager.GetString("ContactComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string ContactFirstName {
            get {
                return ResourceManager.GetString("ContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name of the contact can contain maximum 150 characters..
        /// </summary>
        public static string ContactFirstNameRange {
            get {
                return ResourceManager.GetString("ContactFirstNameRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name of the contact is required..
        /// </summary>
        public static string ContactFirstNameRequired {
            get {
                return ResourceManager.GetString("ContactFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Contact.
        /// </summary>
        public static string ContactIsMain {
            get {
                return ResourceManager.GetString("ContactIsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Language.
        /// </summary>
        public static string ContactLanguage {
            get {
                return ResourceManager.GetString("ContactLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language is required..
        /// </summary>
        public static string ContactLanguageRequired {
            get {
                return ResourceManager.GetString("ContactLanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string ContactLastName {
            get {
                return ResourceManager.GetString("ContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name of the contact can contain maximum 150 characters..
        /// </summary>
        public static string ContactLastNameRange {
            get {
                return ResourceManager.GetString("ContactLastNameRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name of the contact is required..
        /// </summary>
        public static string ContactLastNameRequired {
            get {
                return ResourceManager.GetString("ContactLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation.
        /// </summary>
        public static string ContactPrefix {
            get {
                return ResourceManager.GetString("ContactPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last salutation of the contact can contain maximum 150 characters..
        /// </summary>
        public static string ContactPrefixRange {
            get {
                return ResourceManager.GetString("ContactPrefixRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string ContactToolInfo {
            get {
                return ResourceManager.GetString("ContactToolInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ContactToolToolValue {
            get {
                return ResourceManager.GetString("ContactToolToolValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence of configurations contains overlaps..
        /// </summary>
        public static string ContractModelConfigurationsInvalid {
            get {
                return ResourceManager.GetString("ContractModelConfigurationsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ContractModelName {
            get {
                return ResourceManager.GetString("ContractModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is required..
        /// </summary>
        public static string ContractModelNameRequired {
            get {
                return ResourceManager.GetString("ContractModelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeZone.
        /// </summary>
        public static string ContractModelTimeZoneId {
            get {
                return ResourceManager.GetString("ContractModelTimeZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string ContractModelValidFrom {
            get {
                return ResourceManager.GetString("ContractModelValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string ContractModelValidTo {
            get {
                return ResourceManager.GetString("ContractModelValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string CredentialsId {
            get {
                return ResourceManager.GetString("CredentialsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string CredentialsLogin {
            get {
                return ResourceManager.GetString("CredentialsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password hash.
        /// </summary>
        public static string CredentialsPasswordHash {
            get {
                return ResourceManager.GetString("CredentialsPasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment booking by {0} on {1} at {2}..
        /// </summary>
        public static string DisplayAuditMessage {
            get {
                return ResourceManager.GetString("DisplayAuditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered by {0} {1} on {2} at {3}.
        /// </summary>
        public static string HistoryDisplayAudit {
            get {
                return ResourceManager.GetString("HistoryDisplayAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located on {0} {1} {2}, {3} {4}..
        /// </summary>
        public static string LocationAddressDisplay {
            get {
                return ResourceManager.GetString("LocationAddressDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located on latitude {0} and longitude {1}..
        /// </summary>
        public static string LocationCoordinatesDisplay {
            get {
                return ResourceManager.GetString("LocationCoordinatesDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LocationLatitude {
            get {
                return ResourceManager.GetString("LocationLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latitude has to range from 0° to 90°..
        /// </summary>
        public static string LocationLatitudeRange {
            get {
                return ResourceManager.GetString("LocationLatitudeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latitude of the location is requred..
        /// </summary>
        public static string LocationLatitudeRequired {
            get {
                return ResourceManager.GetString("LocationLatitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location reference.
        /// </summary>
        public static string LocationLocationRef {
            get {
                return ResourceManager.GetString("LocationLocationRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LocationLongitude {
            get {
                return ResourceManager.GetString("LocationLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The longitude has to range from -180° to 180°..
        /// </summary>
        public static string LocationLongitudeRange {
            get {
                return ResourceManager.GetString("LocationLongitudeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The longitude of the location is required..
        /// </summary>
        public static string LocationLongitudeRequired {
            get {
                return ResourceManager.GetString("LocationLongitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The longitude of the location is required..
        /// </summary>
        public static string LocationLongitureRequired {
            get {
                return ResourceManager.GetString("LocationLongitureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string ModuleActionName {
            get {
                return ResourceManager.GetString("ModuleActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductCommercialName {
            get {
                return ResourceManager.GetString("ProductCommercialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regionaam.
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered by {0} {1} on {2} at {3}.
        /// </summary>
        public static string RemarkDisplayAudit {
            get {
                return ResourceManager.GetString("RemarkDisplayAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string RemarkText {
            get {
                return ResourceManager.GetString("RemarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text of the remark is required..
        /// </summary>
        public static string RemarkTextRequired {
            get {
                return ResourceManager.GetString("RemarkTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark type.
        /// </summary>
        public static string RemarkType {
            get {
                return ResourceManager.GetString("RemarkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the remark is required..
        /// </summary>
        public static string RemarkTypeRequired {
            get {
                return ResourceManager.GetString("RemarkTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Category.
        /// </summary>
        public static string ResultCategoryName {
            get {
                return ResourceManager.GetString("ResultCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Code.
        /// </summary>
        public static string ResultCodeCode {
            get {
                return ResourceManager.GetString("ResultCodeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Description.
        /// </summary>
        public static string ResultCodeDescription {
            get {
                return ResourceManager.GetString("ResultCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string ResultCodeOutcomeAbort {
            get {
                return ResourceManager.GetString("ResultCodeOutcomeAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ResultCodeOutcomeDone {
            get {
                return ResourceManager.GetString("ResultCodeOutcomeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string ResultCodeOutcomeNotSet {
            get {
                return ResourceManager.GetString("ResultCodeOutcomeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string ResultCodeOutcomeRedo {
            get {
                return ResourceManager.GetString("ResultCodeOutcomeRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call agent.
        /// </summary>
        public static string RoleTypeCallAgent {
            get {
                return ResourceManager.GetString("RoleTypeCallAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity requestor.
        /// </summary>
        public static string RoleTypeCapacityRequestor {
            get {
                return ResourceManager.GetString("RoleTypeCapacityRequestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator contracting company.
        /// </summary>
        public static string RoleTypeContractingAdmin {
            get {
                return ResourceManager.GetString("RoleTypeContractingAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator contractor.
        /// </summary>
        public static string RoleTypeContractorAdmin {
            get {
                return ResourceManager.GetString("RoleTypeContractorAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatcher.
        /// </summary>
        public static string RoleTypeDispatcher {
            get {
                return ResourceManager.GetString("RoleTypeDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string RoleTypeTechnician {
            get {
                return ResourceManager.GetString("RoleTypeTechnician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect.
        /// </summary>
        public static string SchedulingModeCollect {
            get {
                return ResourceManager.GetString("SchedulingModeCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string SchedulingModeNormal {
            get {
                return ResourceManager.GetString("SchedulingModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string SchedulingModePool {
            get {
                return ResourceManager.GetString("SchedulingModePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string SchedulingModeUrgent {
            get {
                return ResourceManager.GetString("SchedulingModeUrgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with appointment.
        /// </summary>
        public static string SchedulingWithAppointmentCaption {
            get {
                return ResourceManager.GetString("SchedulingWithAppointmentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to without appointment.
        /// </summary>
        public static string SchedulingWithoutAppointmentCaption {
            get {
                return ResourceManager.GetString("SchedulingWithoutAppointmentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order date is required..
        /// </summary>
        public static string ServiceOrderDateRequired {
            get {
                return ResourceManager.GetString("ServiceOrderDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service order {0} with status {1} .
        /// </summary>
        public static string ServiceOrderDisplayString1 {
            get {
                return ResourceManager.GetString("ServiceOrderDisplayString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ordered on {0}.
        /// </summary>
        public static string ServiceOrderDisplayString2 {
            get {
                return ResourceManager.GetString("ServiceOrderDisplayString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The earliest start date is required..
        /// </summary>
        public static string ServiceOrderEaliestDateRequired {
            get {
                return ResourceManager.GetString("ServiceOrderEaliestDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External reference [service order].
        /// </summary>
        public static string ServiceOrderExternalRef {
            get {
                return ResourceManager.GetString("ServiceOrderExternalRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external reference is required..
        /// </summary>
        public static string ServiceOrderExternalRefRequired {
            get {
                return ResourceManager.GetString("ServiceOrderExternalRefRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date [service order].
        /// </summary>
        public static string ServiceOrderOrderDate {
            get {
                return ResourceManager.GetString("ServiceOrderOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The earliest start date shoud be set after the order date..
        /// </summary>
        public static string ServiceOrderStartBeforeOrderDate {
            get {
                return ResourceManager.GetString("ServiceOrderStartBeforeOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest start date.
        /// </summary>
        public static string ServiceOrderStartNoEarlierThan {
            get {
                return ResourceManager.GetString("ServiceOrderStartNoEarlierThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ServiceSpecificationCode {
            get {
                return ResourceManager.GetString("ServiceSpecificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ServiceSpecificationDescription {
            get {
                return ResourceManager.GetString("ServiceSpecificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end time of a shift should be set after the start time..
        /// </summary>
        public static string ShiftFromAfterTo {
            get {
                return ResourceManager.GetString("ShiftFromAfterTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time of a shift is required..
        /// </summary>
        public static string ShiftFromRequired {
            get {
                return ResourceManager.GetString("ShiftFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end time of a shift is required..
        /// </summary>
        public static string ShiftUntilRequired {
            get {
                return ResourceManager.GetString("ShiftUntilRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract model.
        /// </summary>
        public static string SkillDefinitionContractModelId {
            get {
                return ResourceManager.GetString("SkillDefinitionContractModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill definition id.
        /// </summary>
        public static string SkillDefinitionId {
            get {
                return ResourceManager.GetString("SkillDefinitionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is certification needed.
        /// </summary>
        public static string SkillDefinitionIsCertificationNeeded {
            get {
                return ResourceManager.GetString("SkillDefinitionIsCertificationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill name.
        /// </summary>
        public static string SkillDefinitionName {
            get {
                return ResourceManager.GetString("SkillDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Id.
        /// </summary>
        public static string SkillId {
            get {
                return ResourceManager.GetString("SkillId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCertified.
        /// </summary>
        public static string SkillIsCertified {
            get {
                return ResourceManager.GetString("SkillIsCertified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proficiency.
        /// </summary>
        public static string SkillProficiency {
            get {
                return ResourceManager.GetString("SkillProficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill definition.
        /// </summary>
        public static string SkillSkillDefinitionId {
            get {
                return ResourceManager.GetString("SkillSkillDefinitionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Role.
        /// </summary>
        public static string SkillTechnicianRoleId {
            get {
                return ResourceManager.GetString("SkillTechnicianRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        public static string SkillValidFrom {
            get {
                return ResourceManager.GetString("SkillValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        public static string SkillValidUntil {
            get {
                return ResourceManager.GetString("SkillValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string TaskSpecificationCode {
            get {
                return ResourceManager.GetString("TaskSpecificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TaskSpecificationDescription {
            get {
                return ResourceManager.GetString("TaskSpecificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        public static string TaskStatusAborted {
            get {
                return ResourceManager.GetString("TaskStatusAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        public static string TaskStatusEnded {
            get {
                return ResourceManager.GetString("TaskStatusEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string TaskStatusNew {
            get {
                return ResourceManager.GetString("TaskStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician address.
        /// </summary>
        public static string TechnicianAddressAddressId {
            get {
                return ResourceManager.GetString("TechnicianAddressAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician address id.
        /// </summary>
        public static string TechnicianAddressId {
            get {
                return ResourceManager.GetString("TechnicianAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is default.
        /// </summary>
        public static string TechnicianAddressIsDefault {
            get {
                return ResourceManager.GetString("TechnicianAddressIsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string TechnicianAddressTechnicianId {
            get {
                return ResourceManager.GetString("TechnicianAddressTechnicianId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TechnicianAddressType.
        /// </summary>
        public static string TechnicianAddressType {
            get {
                return ResourceManager.GetString("TechnicianAddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        public static string TechnicianAddressTypeFriend {
            get {
                return ResourceManager.GetString("TechnicianAddressTypeFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string TechnicianAddressTypeHoliday {
            get {
                return ResourceManager.GetString("TechnicianAddressTypeHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TechnicianAddressTypeHome {
            get {
                return ResourceManager.GetString("TechnicianAddressTypeHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        public static string TechnicianAddressValidFrom {
            get {
                return ResourceManager.GetString("TechnicianAddressValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        public static string TechnicianAddressValidUntil {
            get {
                return ResourceManager.GetString("TechnicianAddressValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kg.
        /// </summary>
        public static string UnitTypeKg {
            get {
                return ResourceManager.GetString("UnitTypeKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liter.
        /// </summary>
        public static string UnitTypeLiter {
            get {
                return ResourceManager.GetString("UnitTypeLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        public static string UnitTypeMeter {
            get {
                return ResourceManager.GetString("UnitTypeMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string UnitTypeMinutes {
            get {
                return ResourceManager.GetString("UnitTypeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces.
        /// </summary>
        public static string UnitTypePieces {
            get {
                return ResourceManager.GetString("UnitTypePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string UserLastName {
            get {
                return ResourceManager.GetString("UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobilePhone.
        /// </summary>
        public static string UserMobilePhone {
            get {
                return ResourceManager.GetString("UserMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordHash.
        /// </summary>
        public static string UserPasswordHash {
            get {
                return ResourceManager.GetString("UserPasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordSalt.
        /// </summary>
        public static string UserPasswordSalt {
            get {
                return ResourceManager.GetString("UserPasswordSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit {0} [{1}] planned at {2}..
        /// </summary>
        public static string VisitDisplayString1 {
            get {
                return ResourceManager.GetString("VisitDisplayString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed by {0} at {1}..
        /// </summary>
        public static string VisitDisplayString2 {
            get {
                return ResourceManager.GetString("VisitDisplayString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitHistoryReason.
        /// </summary>
        public static string VisitHistoryReason {
            get {
                return ResourceManager.GetString("VisitHistoryReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string VisitLabelId {
            get {
                return ResourceManager.GetString("VisitLabelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultcode not supplied.
        /// </summary>
        public static string VisitNoResultCodeOnEndedStatus {
            get {
                return ResourceManager.GetString("VisitNoResultCodeOnEndedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The planned end is required..
        /// </summary>
        public static string VisitPlannedEndRequired {
            get {
                return ResourceManager.GetString("VisitPlannedEndRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string VisitPlannedStart {
            get {
                return ResourceManager.GetString("VisitPlannedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The planned end shoud be set after the planned start..
        /// </summary>
        public static string VisitPlannedStartBeforeEnd {
            get {
                return ResourceManager.GetString("VisitPlannedStartBeforeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The planned start is required..
        /// </summary>
        public static string VisitPlannedStartRequired {
            get {
                return ResourceManager.GetString("VisitPlannedStartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signer.
        /// </summary>
        public static string VisitSignatureName {
            get {
                return ResourceManager.GetString("VisitSignatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string VisitSignatureUri {
            get {
                return ResourceManager.GetString("VisitSignatureUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        public static string VisitStatusAborted {
            get {
                return ResourceManager.GetString("VisitStatusAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string VisitStatusAccepted {
            get {
                return ResourceManager.GetString("VisitStatusAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocated.
        /// </summary>
        public static string VisitStatusAllocated {
            get {
                return ResourceManager.GetString("VisitStatusAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committed.
        /// </summary>
        public static string VisitStatusCommitted {
            get {
                return ResourceManager.GetString("VisitStatusCommitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        public static string VisitStatusEnded {
            get {
                return ResourceManager.GetString("VisitStatusEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnSite.
        /// </summary>
        public static string VisitStatusOnSite {
            get {
                return ResourceManager.GetString("VisitStatusOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travelling.
        /// </summary>
        public static string VisitStatusTravelling {
            get {
                return ResourceManager.GetString("VisitStatusTravelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unallocated.
        /// </summary>
        public static string VisitStatusUnallocated {
            get {
                return ResourceManager.GetString("VisitStatusUnallocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window end.
        /// </summary>
        public static string VisitWindowEnd {
            get {
                return ResourceManager.GetString("VisitWindowEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window end is required..
        /// </summary>
        public static string VisitWindowEndRequired {
            get {
                return ResourceManager.GetString("VisitWindowEndRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window start.
        /// </summary>
        public static string VisitWindowStart {
            get {
                return ResourceManager.GetString("VisitWindowStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window end shoud be set after the window start..
        /// </summary>
        public static string VisitWindowStartBeforeEnd {
            get {
                return ResourceManager.GetString("VisitWindowStartBeforeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window start is required..
        /// </summary>
        public static string VisitWindowStartRequired {
            get {
                return ResourceManager.GetString("VisitWindowStartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string WorkDayDate {
            get {
                return ResourceManager.GetString("WorkDayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End address.
        /// </summary>
        public static string WorkDayEndTechnicianAddressId {
            get {
                return ResourceManager.GetString("WorkDayEndTechnicianAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work day id.
        /// </summary>
        public static string WorkDayId {
            get {
                return ResourceManager.GetString("WorkDayId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string WorkDayShiftId {
            get {
                return ResourceManager.GetString("WorkDayShiftId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string WorkDayTechnicianAddressId {
            get {
                return ResourceManager.GetString("WorkDayTechnicianAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string WorkDayTechnicianId {
            get {
                return ResourceManager.GetString("WorkDayTechnicianId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work order {0} with status {1} .
        /// </summary>
        public static string WorkOrderDisplayString1 {
            get {
                return ResourceManager.GetString("WorkOrderDisplayString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to based upon specification {0}..
        /// </summary>
        public static string WorkOrderDisplayString2 {
            get {
                return ResourceManager.GetString("WorkOrderDisplayString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External reference [work order].
        /// </summary>
        public static string WorkOrderExternalRef {
            get {
                return ResourceManager.GetString("WorkOrderExternalRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external reference is required..
        /// </summary>
        public static string WorkOrderExternalRefRequired {
            get {
                return ResourceManager.GetString("WorkOrderExternalRefRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string WorkOrderId {
            get {
                return ResourceManager.GetString("WorkOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location id.
        /// </summary>
        public static string WorkOrderLocationId {
            get {
                return ResourceManager.GetString("WorkOrderLocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority [work order].
        /// </summary>
        public static string WorkOrderPriority {
            get {
                return ResourceManager.GetString("WorkOrderPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vist must have a Result Code when in Ended state..
        /// </summary>
        public static string WorkOrderResultCodeRequired {
            get {
                return ResourceManager.GetString("WorkOrderResultCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order id.
        /// </summary>
        public static string WorkOrderServiceOrderId {
            get {
                return ResourceManager.GetString("WorkOrderServiceOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification id.
        /// </summary>
        public static string WorkOrderSpecificationId {
            get {
                return ResourceManager.GetString("WorkOrderSpecificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string WorkOrderStatus {
            get {
                return ResourceManager.GetString("WorkOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work specification is requried..
        /// </summary>
        public static string WorkOrderWorkSpecificationRequired {
            get {
                return ResourceManager.GetString("WorkOrderWorkSpecificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code [work specification].
        /// </summary>
        public static string WorkSpecificationCode {
            get {
                return ResourceManager.GetString("WorkSpecificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description [work specification].
        /// </summary>
        public static string WorkSpecificationDescription {
            get {
                return ResourceManager.GetString("WorkSpecificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id [Work specification].
        /// </summary>
        public static string WorkSpecificationId {
            get {
                return ResourceManager.GetString("WorkSpecificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule mode [work specification].
        /// </summary>
        public static string WorkSpecificationScheduleMode {
            get {
                return ResourceManager.GetString("WorkSpecificationScheduleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service specification [work specification].
        /// </summary>
        public static string WorkSpecificationServiceSpecificationId {
            get {
                return ResourceManager.GetString("WorkSpecificationServiceSpecificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from [work specification].
        /// </summary>
        public static string WorkSpecificationValidFrom {
            get {
                return ResourceManager.GetString("WorkSpecificationValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid to [work specification].
        /// </summary>
        public static string WorkSpecificationValidTo {
            get {
                return ResourceManager.GetString("WorkSpecificationValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With appointment [work specification].
        /// </summary>
        public static string WorkSpecificationWithAppointment {
            get {
                return ResourceManager.GetString("WorkSpecificationWithAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule mode.
        /// </summary>
        public static string WorkSpecificationWithScheduleMode {
            get {
                return ResourceManager.GetString("WorkSpecificationWithScheduleMode", resourceCulture);
            }
        }
    }
}
