//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCruiser.Model.Entities
{
    using System;
    
    public enum UserRoleType : int
    {
        UserRole = 0,
        TechnicianRole = 1
    }
}
