//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCruiser.Model.Entities.Data
{
    using System;
    
    public enum TaskStatusType : int
    {
        New = 0,
        Closed = 1,
        Aborted = 2
    }
}
